# Generated by Django 2.2.13 on 2020-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fftrghy64rjr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfewergw', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gtjguy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsdyw4y5w', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HHHhgfhfhgf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kjhjkhkh', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JHGJGJG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhgjgjh', models.BigIntegerField()),
            ],
        ),
    ]
